image: node:latest # lightweight base image

pages:
  stage: deploy
  script:
    - echo "Building siteâ€¦"
    - npm install
    - npm run build
    - mv out/* public/
  artifacts:
    paths:
      - public # GitLab Pages serves everything under this folder
  # only:
  # - main # or whatever branch you publish from
